services:

  # Twig
  dbout.helper_bundle.twig:
    class: Dbout\Bundle\SymfonyHelperBundle\Twig\Extension\DboutSymfonyHelperTwig
    arguments: ['@dbout.helper_bundle.routing', '@dbout.helper_bundle.pagination']
    tags:
      - {name: twig.extension}

  # Routing
  dbout.helper_bundle.routing:
    class : Dbout\Bundle\SymfonyHelperBundle\Helper\Routing\RoutingHelper
    public: true
    arguments: ['@request_stack', '@router.default']
  Dbout\Bundle\SymfonyHelperBundle\Helper\Routing\RoutingHelper: '@dbout.helper_bundle.routing'

  # Path
  dbout.helper_bundle.path:
    class: Dbout\Bundle\SymfonyHelperBundle\Helper\Path\PathHelper
    public: true
    arguments: ['@kernel']
  Dbout\Bundle\SymfonyHelperBundle\Helper\Path\PathHelper: '@dbout.helper_bundle.path'

  # Pagination Helper
  dbout.helper_bundle.pagination:
    class: Dbout\Bundle\SymfonyHelperBundle\Helper\PaginationHelper
    public: true
    arguments: ['@router.default', '@request_stack']
  Dbout\Bundle\SymfonyHelperBundle\Helper\PaginationHelper: '@dbout.helper_bundle.pagination'

  # Mailer
  dbout.bundle.abstract_mailer:
    class: Dbout\Bundle\SymfonyHelperBundle\Mailer\AbstractMailer
    abstract: true
    calls:
      - [_init]

  # Event listener
  Dbout\Bundle\SymfonyHelperBundle\EventListener\Entity\EntitySubscriber:
    tags:
      - { name: 'doctrine.event_subscriber' }

  # Form Type
  dbout.helper_bundle.form.type:
    class: Dbout\Bundle\SymfonyHelperBundle\Form\Type\SubmitWithSvgIconType
    arguments: ['@service_container']
    tags:
      - {name: form.type}